#include "core/LanguageCatalog.h"

#include <algorithm>

namespace translunix {

const QVector<Language>& LanguageCatalog::all() {
    static const QVector<Language> languages = [] {
        QVector<Language> values = {
            {QStringLiteral("ab"), QStringLiteral("Abkhazian")},
            {QStringLiteral("aa"), QStringLiteral("Afar")},
            {QStringLiteral("af"), QStringLiteral("Afrikaans")},
            {QStringLiteral("ak"), QStringLiteral("Akan")},
            {QStringLiteral("sq"), QStringLiteral("Albanian")},
            {QStringLiteral("am"), QStringLiteral("Amharic")},
            {QStringLiteral("ar"), QStringLiteral("Arabic")},
            {QStringLiteral("an"), QStringLiteral("Aragonese")},
            {QStringLiteral("hy"), QStringLiteral("Armenian")},
            {QStringLiteral("as"), QStringLiteral("Assamese")},
            {QStringLiteral("av"), QStringLiteral("Avaric")},
            {QStringLiteral("ae"), QStringLiteral("Avestan")},
            {QStringLiteral("ay"), QStringLiteral("Aymara")},
            {QStringLiteral("az"), QStringLiteral("Azerbaijani")},
            {QStringLiteral("bm"), QStringLiteral("Bambara")},
            {QStringLiteral("ba"), QStringLiteral("Bashkir")},
            {QStringLiteral("eu"), QStringLiteral("Basque")},
            {QStringLiteral("be"), QStringLiteral("Belarusian")},
            {QStringLiteral("bn"), QStringLiteral("Bengali")},
            {QStringLiteral("bi"), QStringLiteral("Bislama")},
            {QStringLiteral("bs"), QStringLiteral("Bosnian")},
            {QStringLiteral("br"), QStringLiteral("Breton")},
            {QStringLiteral("bg"), QStringLiteral("Bulgarian")},
            {QStringLiteral("my"), QStringLiteral("Burmese")},
            {QStringLiteral("ca"), QStringLiteral("Catalan")},
            {QStringLiteral("ch"), QStringLiteral("Chamorro")},
            {QStringLiteral("ce"), QStringLiteral("Chechen")},
            {QStringLiteral("ny"), QStringLiteral("Chichewa")},
            {QStringLiteral("zh"), QStringLiteral("Chinese")},
            {QStringLiteral("zh-Hans"), QStringLiteral("Chinese, Simplified")},
            {QStringLiteral("zh-Hant"), QStringLiteral("Chinese, Traditional")},
            {QStringLiteral("cu"), QStringLiteral("Church Slavic")},
            {QStringLiteral("cv"), QStringLiteral("Chuvash")},
            {QStringLiteral("kw"), QStringLiteral("Cornish")},
            {QStringLiteral("co"), QStringLiteral("Corsican")},
            {QStringLiteral("cr"), QStringLiteral("Cree")},
            {QStringLiteral("hr"), QStringLiteral("Croatian")},
            {QStringLiteral("cs"), QStringLiteral("Czech")},
            {QStringLiteral("da"), QStringLiteral("Danish")},
            {QStringLiteral("dv"), QStringLiteral("Divehi")},
            {QStringLiteral("nl"), QStringLiteral("Dutch")},
            {QStringLiteral("dz"), QStringLiteral("Dzongkha")},
            {QStringLiteral("en"), QStringLiteral("English")},
            {QStringLiteral("eo"), QStringLiteral("Esperanto")},
            {QStringLiteral("et"), QStringLiteral("Estonian")},
            {QStringLiteral("ee"), QStringLiteral("Ewe")},
            {QStringLiteral("fo"), QStringLiteral("Faroese")},
            {QStringLiteral("fj"), QStringLiteral("Fijian")},
            {QStringLiteral("fil"), QStringLiteral("Filipino")},
            {QStringLiteral("fi"), QStringLiteral("Finnish")},
            {QStringLiteral("fr"), QStringLiteral("French")},
            {QStringLiteral("ff"), QStringLiteral("Fulah")},
            {QStringLiteral("gl"), QStringLiteral("Galician")},
            {QStringLiteral("ka"), QStringLiteral("Georgian")},
            {QStringLiteral("de"), QStringLiteral("German")},
            {QStringLiteral("el"), QStringLiteral("Greek")},
            {QStringLiteral("gn"), QStringLiteral("Guarani")},
            {QStringLiteral("gu"), QStringLiteral("Gujarati")},
            {QStringLiteral("ht"), QStringLiteral("Haitian Creole")},
            {QStringLiteral("ha"), QStringLiteral("Hausa")},
            {QStringLiteral("he"), QStringLiteral("Hebrew")},
            {QStringLiteral("hz"), QStringLiteral("Herero")},
            {QStringLiteral("hi"), QStringLiteral("Hindi")},
            {QStringLiteral("ho"), QStringLiteral("Hiri Motu")},
            {QStringLiteral("hu"), QStringLiteral("Hungarian")},
            {QStringLiteral("is"), QStringLiteral("Icelandic")},
            {QStringLiteral("io"), QStringLiteral("Ido")},
            {QStringLiteral("ig"), QStringLiteral("Igbo")},
            {QStringLiteral("id"), QStringLiteral("Indonesian")},
            {QStringLiteral("ia"), QStringLiteral("Interlingua")},
            {QStringLiteral("ie"), QStringLiteral("Interlingue")},
            {QStringLiteral("iu"), QStringLiteral("Inuktitut")},
            {QStringLiteral("ik"), QStringLiteral("Inupiaq")},
            {QStringLiteral("ga"), QStringLiteral("Irish")},
            {QStringLiteral("it"), QStringLiteral("Italian")},
            {QStringLiteral("ja"), QStringLiteral("Japanese")},
            {QStringLiteral("jv"), QStringLiteral("Javanese")},
            {QStringLiteral("kl"), QStringLiteral("Kalaallisut")},
            {QStringLiteral("kn"), QStringLiteral("Kannada")},
            {QStringLiteral("kr"), QStringLiteral("Kanuri")},
            {QStringLiteral("ks"), QStringLiteral("Kashmiri")},
            {QStringLiteral("kk"), QStringLiteral("Kazakh")},
            {QStringLiteral("km"), QStringLiteral("Khmer")},
            {QStringLiteral("ki"), QStringLiteral("Kikuyu")},
            {QStringLiteral("rw"), QStringLiteral("Kinyarwanda")},
            {QStringLiteral("ky"), QStringLiteral("Kyrgyz")},
            {QStringLiteral("kv"), QStringLiteral("Komi")},
            {QStringLiteral("kg"), QStringLiteral("Kongo")},
            {QStringLiteral("ko"), QStringLiteral("Korean")},
            {QStringLiteral("kj"), QStringLiteral("Kuanyama")},
            {QStringLiteral("ku"), QStringLiteral("Kurdish")},
            {QStringLiteral("ckb"), QStringLiteral("Kurdish, Sorani")},
            {QStringLiteral("lo"), QStringLiteral("Lao")},
            {QStringLiteral("la"), QStringLiteral("Latin")},
            {QStringLiteral("lv"), QStringLiteral("Latvian")},
            {QStringLiteral("li"), QStringLiteral("Limburgish")},
            {QStringLiteral("ln"), QStringLiteral("Lingala")},
            {QStringLiteral("lt"), QStringLiteral("Lithuanian")},
            {QStringLiteral("lu"), QStringLiteral("Luba-Katanga")},
            {QStringLiteral("lb"), QStringLiteral("Luxembourgish")},
            {QStringLiteral("mk"), QStringLiteral("Macedonian")},
            {QStringLiteral("mg"), QStringLiteral("Malagasy")},
            {QStringLiteral("ms"), QStringLiteral("Malay")},
            {QStringLiteral("ml"), QStringLiteral("Malayalam")},
            {QStringLiteral("mt"), QStringLiteral("Maltese")},
            {QStringLiteral("gv"), QStringLiteral("Manx")},
            {QStringLiteral("mi"), QStringLiteral("Maori")},
            {QStringLiteral("mr"), QStringLiteral("Marathi")},
            {QStringLiteral("mh"), QStringLiteral("Marshallese")},
            {QStringLiteral("mn"), QStringLiteral("Mongolian")},
            {QStringLiteral("na"), QStringLiteral("Nauru")},
            {QStringLiteral("nv"), QStringLiteral("Navajo")},
            {QStringLiteral("nd"), QStringLiteral("North Ndebele")},
            {QStringLiteral("nr"), QStringLiteral("South Ndebele")},
            {QStringLiteral("ng"), QStringLiteral("Ndonga")},
            {QStringLiteral("ne"), QStringLiteral("Nepali")},
            {QStringLiteral("se"), QStringLiteral("Northern Sami")},
            {QStringLiteral("no"), QStringLiteral("Norwegian")},
            {QStringLiteral("nb"), QStringLiteral("Norwegian Bokmal")},
            {QStringLiteral("nn"), QStringLiteral("Norwegian Nynorsk")},
            {QStringLiteral("oc"), QStringLiteral("Occitan")},
            {QStringLiteral("oj"), QStringLiteral("Ojibwe")},
            {QStringLiteral("or"), QStringLiteral("Odia")},
            {QStringLiteral("om"), QStringLiteral("Oromo")},
            {QStringLiteral("os"), QStringLiteral("Ossetian")},
            {QStringLiteral("pi"), QStringLiteral("Pali")},
            {QStringLiteral("ps"), QStringLiteral("Pashto")},
            {QStringLiteral("fa"), QStringLiteral("Persian")},
            {QStringLiteral("pl"), QStringLiteral("Polish")},
            {QStringLiteral("pt"), QStringLiteral("Portuguese")},
            {QStringLiteral("pa"), QStringLiteral("Punjabi")},
            {QStringLiteral("qu"), QStringLiteral("Quechua")},
            {QStringLiteral("ro"), QStringLiteral("Romanian")},
            {QStringLiteral("rm"), QStringLiteral("Romansh")},
            {QStringLiteral("rn"), QStringLiteral("Rundi")},
            {QStringLiteral("ru"), QStringLiteral("Russian")},
            {QStringLiteral("sm"), QStringLiteral("Samoan")},
            {QStringLiteral("sg"), QStringLiteral("Sango")},
            {QStringLiteral("sa"), QStringLiteral("Sanskrit")},
            {QStringLiteral("sc"), QStringLiteral("Sardinian")},
            {QStringLiteral("gd"), QStringLiteral("Scottish Gaelic")},
            {QStringLiteral("sr"), QStringLiteral("Serbian")},
            {QStringLiteral("sn"), QStringLiteral("Shona")},
            {QStringLiteral("ii"), QStringLiteral("Sichuan Yi")},
            {QStringLiteral("sd"), QStringLiteral("Sindhi")},
            {QStringLiteral("si"), QStringLiteral("Sinhala")},
            {QStringLiteral("sk"), QStringLiteral("Slovak")},
            {QStringLiteral("sl"), QStringLiteral("Slovenian")},
            {QStringLiteral("so"), QStringLiteral("Somali")},
            {QStringLiteral("st"), QStringLiteral("Southern Sotho")},
            {QStringLiteral("es"), QStringLiteral("Spanish")},
            {QStringLiteral("su"), QStringLiteral("Sundanese")},
            {QStringLiteral("sw"), QStringLiteral("Swahili")},
            {QStringLiteral("ss"), QStringLiteral("Swati")},
            {QStringLiteral("sv"), QStringLiteral("Swedish")},
            {QStringLiteral("tl"), QStringLiteral("Tagalog")},
            {QStringLiteral("ty"), QStringLiteral("Tahitian")},
            {QStringLiteral("tg"), QStringLiteral("Tajik")},
            {QStringLiteral("ta"), QStringLiteral("Tamil")},
            {QStringLiteral("tt"), QStringLiteral("Tatar")},
            {QStringLiteral("te"), QStringLiteral("Telugu")},
            {QStringLiteral("th"), QStringLiteral("Thai")},
            {QStringLiteral("bo"), QStringLiteral("Tibetan")},
            {QStringLiteral("ti"), QStringLiteral("Tigrinya")},
            {QStringLiteral("to"), QStringLiteral("Tonga")},
            {QStringLiteral("ts"), QStringLiteral("Tsonga")},
            {QStringLiteral("tn"), QStringLiteral("Tswana")},
            {QStringLiteral("tr"), QStringLiteral("Turkish")},
            {QStringLiteral("tk"), QStringLiteral("Turkmen")},
            {QStringLiteral("tw"), QStringLiteral("Twi")},
            {QStringLiteral("ug"), QStringLiteral("Uyghur")},
            {QStringLiteral("uk"), QStringLiteral("Ukrainian")},
            {QStringLiteral("ur"), QStringLiteral("Urdu")},
            {QStringLiteral("uz"), QStringLiteral("Uzbek")},
            {QStringLiteral("ve"), QStringLiteral("Venda")},
            {QStringLiteral("vi"), QStringLiteral("Vietnamese")},
            {QStringLiteral("vo"), QStringLiteral("Volapuk")},
            {QStringLiteral("wa"), QStringLiteral("Walloon")},
            {QStringLiteral("cy"), QStringLiteral("Welsh")},
            {QStringLiteral("fy"), QStringLiteral("Western Frisian")},
            {QStringLiteral("wo"), QStringLiteral("Wolof")},
            {QStringLiteral("xh"), QStringLiteral("Xhosa")},
            {QStringLiteral("yi"), QStringLiteral("Yiddish")},
            {QStringLiteral("yo"), QStringLiteral("Yoruba")},
            {QStringLiteral("yue"), QStringLiteral("Cantonese")},
            {QStringLiteral("za"), QStringLiteral("Zhuang")},
            {QStringLiteral("zu"), QStringLiteral("Zulu")},
        };
        std::sort(values.begin(), values.end(), [](const Language& left, const Language& right) {
            return QString::localeAwareCompare(left.name, right.name) < 0;
        });
        return values;
    }();
    return languages;
}

std::optional<Language> LanguageCatalog::byCode(const QString& code) {
    const QString normalized = code.trimmed();
    const auto& values = all();
    const auto found = std::find_if(values.cbegin(), values.cend(), [&](const Language& language) {
        return language.code.compare(normalized, Qt::CaseInsensitive) == 0;
    });
    if (found == values.cend()) {
        return std::nullopt;
    }
    return *found;
}

} // namespace translunix
